### ISSUE TITLE
sortAlgo -> sortInPlace

### ISSUE THREAD

**Issue by altavir** [KiberneticWorm/Kotlin-Algorithms-and-Design-Patterns#1]
https://github.com/KiberneticWorm/Kotlin-Algorithms-and-Design-Patterns/blob/b96f19350f2d70a159eb3310acd31697a73d0ac9/src/main/kotlin/en/sorting/SortAlgo.kt#L10

it would be be better to call it `sortInPlace`.

**Comment by KiberneticWorm** [comment]
I'm thinking of just making Kotlin extension functions
