### ISSUE TITLE
Naive factorial implementation

### ISSUE THREAD

**Issue by CommanderTvis** [KiberneticWorm/Kotlin-Algorithms-and-Design-Patterns#6]
The current implementation of factorial has two problems:
1. It demonstrates literally nothing except the factorial's definition. To be meaningful it should contain some optimizations like prime factorization.
2. It uses `Int`, hence it is correct only in [ 0 .. 12 ] range.
![image](https://user-images.githubusercontent.com/38042667/151709167-fe0756e0-9a81-4df1-81e6-05f5a716fcf9.png)
Even using `ULong` will allow values only from 0 to 20 inclusively, so only long arithmetic can have any practical value because for standard integer types the optimal algorithm is just to access array:

```kotlin
val factorials: ULongArray = ulongArrayOf(1uL, 1uL, 2uL ...)
```

**Comment by KiberneticWorm** [comment]
The Second problem has already been solved)
Look at here - https://github.com/KiberneticWorm/Kotlin-Algorithms-and-Design-Patterns/blob/master/src/main/kotlin/other/FactorialBigWithCache.kt

**Comment by KiberneticWorm** [comment]
Can you elaborate on the first point please?

**Comment by CommanderTvis** [comment]
> Can you elaborate on the first point please?

Just google for "efficient factorial algorithm".

**Comment by KiberneticWorm** [comment]
Thanks) I'll do it

**Comment by KiberneticWorm** [comment]
I found more efficient algorithms for factorial, but I couldn't implement it. 
Could you make a pull request?

**Comment by KiberneticWorm** [comment]
I implemented an efficient algorithm (from google guava library)
[FactorialAdvanced](https://github.com/KiberneticWorm/Kotlin-Algorithms-and-Design-Patterns/blob/master/src/main/kotlin/other/FactorialAdvanced.kt)
