### ISSUE TITLE
Palindrome algorithm

### ISSUE THREAD

**Issue by yamin8000** [KiberneticWorm/Kotlin-Algorithms-and-Design-Patterns#7]
https://github.com/KiberneticWorm/Kotlin-Algorithms-and-Design-Patterns/blob/master/src/main/kotlin/other/Palindrome.kt
I don't think this is an algorithm.

**Comment by KiberneticWorm** [comment]
This is algorithm for checking a string for a palindrome! 
I'll add one more implementation
